/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurant;
    import java.text.SimpleDateFormat;
    import java.util.Calendar;
    import java.util.GregorianCalendar;
    import java.awt.Color;
    import java.text.SimpleDateFormat;
    import java.util.Random;

/**
 *
 * @author NICK
 */
public class Restaurants extends javax.swing.JFrame {
    //declaring array i[0]
    //double [] i = new double [5];
    //declaring a string
        double bill;
        double total;

     //declaring the currency operations
    //Kenya_shillings EQUIVALENCE  == 1.00;
    //double Kenya_shillings = 1.00;
    
    double Tanzania_shillings = 22.59;
    double Uganda_shillings = 36.23;
    //double US_Dollars = 0.0098;
    //double Euros = 0.0089;
    //double Sterling_Pound = 0.0075;
    double Congo = 16.50;
    double Rwanda = 9.05;
    //double India = 0.70;
    double Nigeria = 3.57;
    double South_Africa = 0.14;
           
    
    
    //declaring the arithmetic operations
    double firstnum;
    double secondnum;
    double results;
    String operations;
    
    
    /**
     * Creates new form Restaurants
     */
    public Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTxtDisplay = new javax.swing.JTextField();
        jBtn4 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnminus = new javax.swing.JButton();
        jBtnplus = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtntimes = new javax.swing.JButton();
        jBtnover = new javax.swing.JButton();
        jBtnBR = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnpoint = new javax.swing.JButton();
        jBtnequal = new javax.swing.JButton();
        jBtnclear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jChickenGrilled = new javax.swing.JCheckBox();
        jtxtFries = new javax.swing.JCheckBox();
        jBhajia = new javax.swing.JCheckBox();
        jSausage = new javax.swing.JCheckBox();
        jtxtChicken = new javax.swing.JTextField();
        jtxtfries = new javax.swing.JTextField();
        jtxtSausages = new javax.swing.JTextField();
        jtxtBhajia = new javax.swing.JTextField();
        jTxtTax = new javax.swing.JCheckBox();
        jCDelivery = new javax.swing.JCheckBox();
        jTextField10 = new javax.swing.JTextField();
        jCmbDrink = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblCostOfMeal = new javax.swing.JLabel();
        jlblCostOfDrinks = new javax.swing.JLabel();
        jlblDeliveryCost = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtSubtotal = new javax.swing.JLabel();
        jtxtTax = new javax.swing.JLabel();
        jtxtGrandTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jcmbCurrency = new javax.swing.JComboBox<>();
        jtxtConvert = new javax.swing.JTextField();
        jBtnCoverter = new javax.swing.JButton();
        jTxtReset = new javax.swing.JButton();
        jlblConvert = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jBtnReset = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jBtnTotal3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Receipt", jPanel10);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTxtDisplay.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtDisplay.setText("0");
        jTxtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtn4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtnminus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnminus.setText("-");
        jBtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnminusActionPerformed(evt);
            }
        });

        jBtnplus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnplus.setText("+");
        jBtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnplusActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtntimes.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtntimes.setText("*");
        jBtntimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtntimesActionPerformed(evt);
            }
        });

        jBtnover.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnover.setText("/");
        jBtnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnoverActionPerformed(evt);
            }
        });

        jBtnBR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnBR.setText("+/-");
        jBtnBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBRActionPerformed(evt);
            }
        });

        jBtnC.setBackground(new java.awt.Color(255, 0, 0));
        jBtnC.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnC.setForeground(new java.awt.Color(0, 0, 0));
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });

        jBtnpoint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnpoint.setText(".");
        jBtnpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnpointActionPerformed(evt);
            }
        });

        jBtnequal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnequal.setText("=");
        jBtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnequalActionPerformed(evt);
            }
        });

        jBtnclear.setBackground(new java.awt.Color(255, 0, 0));
        jBtnclear.setFont(new java.awt.Font("Wingdings", 1, 18)); // NOI18N
        jBtnclear.setForeground(new java.awt.Color(255, 0, 0));
        jBtnclear.setIcon(new javax.swing.ImageIcon("C:\\Users\\NICK\\Desktop\\freelancer icons\\left-black-arrow.png")); // NOI18N
        jBtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jBtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnover, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtntimes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jBtnpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jBtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnBR, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBR, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtntimes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnover, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("calculator", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChickenGrilled.setText("GRILLED CHICKEN");
        jChickenGrilled.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickenGrilledMouseClicked(evt);
            }
        });
        jChickenGrilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChickenGrilledActionPerformed(evt);
            }
        });

        jtxtFries.setText("FRIES");
        jtxtFries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFriesMouseClicked(evt);
            }
        });
        jtxtFries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFriesActionPerformed(evt);
            }
        });

        jBhajia.setText("BHAJIA");
        jBhajia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBhajiaMouseClicked(evt);
            }
        });
        jBhajia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBhajiaActionPerformed(evt);
            }
        });

        jSausage.setText("SAUSAGES");
        jSausage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSausageMouseClicked(evt);
            }
        });
        jSausage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSausageActionPerformed(evt);
            }
        });

        jtxtChicken.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtChickenMouseClicked(evt);
            }
        });
        jtxtChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenActionPerformed(evt);
            }
        });

        jtxtfries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfriesActionPerformed(evt);
            }
        });

        jTxtTax.setText("TAX");
        jTxtTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtTaxMouseClicked(evt);
            }
        });
        jTxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTaxActionPerformed(evt);
            }
        });

        jCDelivery.setText("HOME DELIVERY");
        jCDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCDeliveryMouseClicked(evt);
            }
        });
        jCDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCDeliveryActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Lucida Bright", 3, 14)); // NOI18N
        jTextField10.setText("DRINKS");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jCmbDrink.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Drink", "Mango juice", "Tropical mix", "orange juice ", "Lemon juice ", "Blended juice", "Pineapple juice", "Apple juice", "Minute maid", "Soda(300ml)", "Soda(500ml)", "Ice Cream", "Tea ", "Black coffee", "White coffee", "Mineral Water(small)", "Mineral Water(large)", "Cocktails(small)", "Cocktails(large)", "JackDaniels", "Konyagi", "KenyaCane", "Chrome", "Heinessy", " ", " " }));
        jCmbDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCmbDrinkMouseClicked(evt);
            }
        });
        jCmbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxtTax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCDelivery))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBhajia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtxtFries, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSausage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addComponent(jChickenGrilled))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtChicken)
                            .addComponent(jtxtSausages, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jtxtfries, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(jtxtBhajia, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChickenGrilled)
                    .addComponent(jtxtChicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFries)
                    .addComponent(jtxtfries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSausage)
                    .addComponent(jtxtSausages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBhajia)
                    .addComponent(jtxtBhajia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTax)
                    .addComponent(jCDelivery))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cost of meal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Delivery Cost");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cost of Drinks");

        jlblCostOfMeal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblCostOfMeal.setText("0");
        jlblCostOfMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblCostOfMealMouseClicked(evt);
            }
        });

        jlblCostOfDrinks.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblCostOfDrinks.setText("0");

        jlblDeliveryCost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblDeliveryCost.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostOfDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblCostOfMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblDeliveryCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jlblCostOfMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDeliveryCost, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("SUBTOTAL");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("TAX");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("TOTAL");

        jtxtSubtotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtSubtotal.setText("0");

        jtxtTax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtTax.setText("0");

        jtxtGrandTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtGrandTotal.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jcmbCurrency.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Currency", "Tanzanian Shilling", "Ugandan Shilling", "Congolese Franc", "Rwandan Franc", "Nigeria Naira", "South African Rand", " ", " " }));

        jtxtConvert.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jtxtConvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnCoverter.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jBtnCoverter.setText("Convert");
        jBtnCoverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCoverterActionPerformed(evt);
            }
        });

        jTxtReset.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jTxtReset.setText("Reset");
        jTxtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtResetActionPerformed(evt);
            }
        });

        jlblConvert.setBackground(new java.awt.Color(102, 102, 102));
        jlblConvert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlblConvert.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblConvert, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBtnCoverter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtReset, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                    .addComponent(jtxtConvert)
                    .addComponent(jcmbCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCoverter, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jTxtReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jBtnReset.setBackground(new java.awt.Color(204, 204, 204));
        jBtnReset.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnReset.setText("RESET");
        jBtnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnResetMouseClicked(evt);
            }
        });
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });

        jBtnReceipt.setBackground(new java.awt.Color(204, 204, 204));
        jBtnReceipt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnReceipt.setText("RECEIPT");
        jBtnReceipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnReceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnReceiptMouseClicked(evt);
            }
        });
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });

        jBtnExit.setBackground(new java.awt.Color(204, 204, 204));
        jBtnExit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnExit.setText("EXIT");
        jBtnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });

        jBtnTotal3.setBackground(new java.awt.Color(204, 204, 204));
        jBtnTotal3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBtnTotal3.setText("TOTAL");
        jBtnTotal3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnTotal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTotal3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel7.setText("NICKY'S RESTAURANT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jCDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCDeliveryActionPerformed

    private void jTxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTaxActionPerformed

    private void jSausageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSausageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSausageActionPerformed

    private void jBhajiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBhajiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBhajiaActionPerformed

    private void jtxtFriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFriesActionPerformed

    private void jChickenGrilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChickenGrilledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChickenGrilledActionPerformed

    private void jBtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnclearActionPerformed
        String backspace=null;
        if (jTxtDisplay.getText ().length () > 0){
            StringBuilder StrB = new StringBuilder (jTxtDisplay.getText());
            StrB.deleteCharAt (jTxtDisplay.getText ().length () -1);
            backspace =StrB.toString();
            jTxtDisplay.setText (backspace);
        }
    }//GEN-LAST:event_jBtnclearActionPerformed

    private void jtxtfriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfriesActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn5.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jtxtfriesActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
            String Enternumber = jTxtDisplay.getText() + jBtn7.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
         String Enternumber = jTxtDisplay.getText() + jBtn8.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn9.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
         String Enternumber = jTxtDisplay.getText() + jBtn4.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        jTxtDisplay.setText (null);
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBRActionPerformed
        double ops = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        ops = ops * (-1);
        jTxtDisplay.setText (String.valueOf (ops));
    }//GEN-LAST:event_jBtnBRActionPerformed

    private void jBtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnplusActionPerformed
           firstnum = Double.parseDouble(jTxtDisplay.getText());
            jTxtDisplay.setText (" ");
            operations = "+";
    }//GEN-LAST:event_jBtnplusActionPerformed

    private void jBtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnminusActionPerformed
            firstnum = Double.parseDouble(jTxtDisplay.getText());
            jTxtDisplay.setText (" ");
            operations = "-";
    }//GEN-LAST:event_jBtnminusActionPerformed

    private void jBtntimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtntimesActionPerformed
           firstnum = Double.parseDouble(jTxtDisplay.getText());
            jTxtDisplay.setText (" ");
            operations = "*";
    }//GEN-LAST:event_jBtntimesActionPerformed

    private void jBtnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnoverActionPerformed
            firstnum = Double.parseDouble(jTxtDisplay.getText());
            jTxtDisplay.setText (" ");
            operations = "/";
        
    }//GEN-LAST:event_jBtnoverActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn0.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn1.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn2.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn3.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn5.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String Enternumber = jTxtDisplay.getText() + jBtn6.getText();
        jTxtDisplay.setText (Enternumber);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtnpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnpointActionPerformed
        jTxtDisplay.setText (jTxtDisplay.getText() + jBtnpoint.getText());
    }//GEN-LAST:event_jBtnpointActionPerformed

    private void jBtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnequalActionPerformed
        String answer;
        secondnum = Double.parseDouble(jTxtDisplay.getText());
        if (operations == "+")
        {
            results = firstnum + secondnum;
            answer = String.format ( "%.2f",results);
            jTxtDisplay.setText (answer);
        }
        
        
        
        else if (operations == "-")
        {
            results = firstnum - secondnum;
            answer = String.format ( "%.2f",results);
            jTxtDisplay.setText (answer);
        }
        
        else if (operations == "*")
        {
            results = firstnum * secondnum;
            answer = String.format ( "%.2f",results);
            jTxtDisplay.setText (answer);
        }
        
        else if (operations == "/")
        {
            results = firstnum / secondnum;
            answer = String.format ( "%.2f",results);
            jTxtDisplay.setText (answer);
        }
        
        else if (operations == "%")
        {
            results = firstnum % secondnum;
            answer = String.format ( "%.2f",results);
            jTxtDisplay.setText (answer);
        }
    }//GEN-LAST:event_jBtnequalActionPerformed

    private void jBtnCoverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCoverterActionPerformed
        double Ksh = Double.parseDouble(jtxtConvert.getText());
        
        if (jcmbCurrency.getSelectedItem().equals("Tanzanian Shilling"))
        {
            String cConvert1 = String.format ("TSH: %.2f",Ksh * Tanzania_shillings );
            jlblConvert.setText(cConvert1);
        }
                
        
        if (jcmbCurrency.getSelectedItem().equals("Ugandan Shilling"))
        {
            String cConvert1 = String.format ("UGSH: %.2f",Ksh * Uganda_shillings );
            jlblConvert.setText(cConvert1);
        }
        
        /*if (jcmbCurrency.getSelectedItem().equals("USD"))
        {
            String cConvert1 = String.format ("$: %.2f",Ksh * US_Dollars );
            jlblConvert.setText(cConvert1);
        }*/
        
        
              
        /*if (jcmbCurrency.getSelectedItem().equals("Euros"))
        {
            String cConvert1 = String.format ("Euro(€): %.2f",Ksh * Euros );
            jlblConvert.setText(cConvert1);
        }*/
               
       
        /*if (jcmbCurrency.getSelectedItem().equals("Sterling Pound"))
        {
            String cConvert1 = String.format ("Pound(£): %.2f",Ksh * Sterling_Pound );
            jlblConvert.setText(cConvert1);
        }*/
        
        if (jcmbCurrency.getSelectedItem().equals("Congolese Franc"))
        {
            String cConvert1 = String.format ("CDF: %.2f",Ksh * Congo );
            jlblConvert.setText(cConvert1);
        }
        
        if (jcmbCurrency.getSelectedItem().equals("Rwandan Franc"))
        {
            String cConvert1 = String.format ("RWF: %.2f",Ksh * Rwanda );
            jlblConvert.setText(cConvert1);
        }
            
        if (jcmbCurrency.getSelectedItem().equals("Nigeria Naira"))
        {
            String cConvert1 = String.format ("Naira(₦): %.2f",Ksh * Nigeria );
            jlblConvert.setText(cConvert1);
        }
        
        if (jcmbCurrency.getSelectedItem().equals("South African Rand"))
        {
            String cConvert1 = String.format ("Rand: %.2f",Ksh * South_Africa );
            jlblConvert.setText(cConvert1);
        }
        
        
        
    }//GEN-LAST:event_jBtnCoverterActionPerformed

    private void jTxtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtResetActionPerformed
        jtxtConvert.setText(null);
        jlblConvert.setText(null);
        jcmbCurrency.setSelectedIndex(0);
    }//GEN-LAST:event_jTxtResetActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnResetActionPerformed
        //select a drink in an order 
    private void jCmbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbDrinkActionPerformed
        double Mango_juice = 100;
        double Tropical_mix = 110;
        double Orange_juice = 90;
        double Lemon_juice = 100;
        double Blended_juice = 110;
        double Pineapple_juice = 100;
        double Apple_juice = 120;
        double Minute_maid = 150;
        double Soda_small = 100;
        double Soda_large = 200;
        double Ice_cream = 100;
        double Tea = 90;
        double Black_coffee = 200;
        double White_coffee = 200;        
        double Mineral_Water_small = 80;
        double Mineral_Water_large = 150;
        double Cocktails_small = 400;
        double Cocktails_large = 800;
        double JackDaniels = 5000;
        double Konyagi = 300;
        double KenyaCane = 300;
        double Chrome = 400;
        double Heinessy = 8000;
        
        
        
        
         if (jCmbDrink.getSelectedItem().equals("Select a Drink"))
        {
            jlblCostOfDrinks.setText(null);
        }
         
                
        if (jCmbDrink.getSelectedItem().equals("Mango juice"))
        {
            String cMangojuice = String.format (" %.2f",Mango_juice );
            jlblCostOfDrinks.setText(cMangojuice);
        }
        
        
        if (jCmbDrink.getSelectedItem().equals("Tropical mix"))
        {
            String cTropicalmix = String.format (" %.2f",Tropical_mix );
            jlblCostOfDrinks.setText(cTropicalmix);
        }
        
        if (jCmbDrink.getSelectedItem().equals("orange juice"))
        {
            String cOrangejuice = String.format (" %.2f",Orange_juice );
            jlblCostOfDrinks.setText(cOrangejuice);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Lemon juice"))
        {
            String cLemonjuice = String.format (" %.2f",Lemon_juice );
            jlblCostOfDrinks.setText(cLemonjuice);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Blended juice"))
        {
            String cBlendedjuice = String.format (" %.2f",Blended_juice );
            jlblCostOfDrinks.setText(cBlendedjuice);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Pineapple juice"))
        {
            String cPineapplejuice = String.format (" %.2f",Pineapple_juice );
            jlblCostOfDrinks.setText(cPineapplejuice);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Apple juice"))
        {
            String cApplejuice = String.format (" %.2f",Apple_juice );
            jlblCostOfDrinks.setText(cApplejuice);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Minute maid"))
        {
            String cMinutemaid = String.format (" %.2f",Minute_maid );
            jlblCostOfDrinks.setText(cMinutemaid);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Soda(300ml)"))
        {
            String cSodasmall = String.format (" %.2f",Soda_small );
            jlblCostOfDrinks.setText(cSodasmall);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Soda"))
        {
            String cSodalarge = String.format (" %.2f",Soda_large );
            jlblCostOfDrinks.setText(cSodalarge);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Ice Cream"))
        {
            String cIcecream = String.format (" %.2f",Ice_cream );
            jlblCostOfDrinks.setText(cIcecream);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Tea"))
        {
            String cTea = String.format (" %.2f",Tea );
            jlblCostOfDrinks.setText(cTea);
        }
        
        if (jCmbDrink.getSelectedItem().equals("White coffee"))
        {
            String cWhitecoffee = String.format (" %.2f",White_coffee );
            jlblCostOfDrinks.setText(cWhitecoffee);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Black coffee"))
        {
            String cBlackcoffee = String.format (" %.2f",Black_coffee );
            jlblCostOfDrinks.setText(cBlackcoffee);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Mineral Water(small)"))
        {
            String cMineralWatersmall = String.format (" %.2f",Mineral_Water_small );
            jlblCostOfDrinks.setText(cMineralWatersmall);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Mineral Water(large)"))
        {
            String cMineralWaterlarge = String.format (" %.2f",Mineral_Water_large );
            jlblCostOfDrinks.setText(cMineralWaterlarge);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Cocktails(small)"))
        {
            String cCocktailssmall = String.format (" %.2f",Cocktails_small );
            jlblCostOfDrinks.setText(cCocktailssmall);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Cocktails(large)"))
        {
            String cCocktailslarge = String.format (" %.2f",Cocktails_large );
            jlblCostOfDrinks.setText(cCocktailslarge);
        }
        
        if (jCmbDrink.getSelectedItem().equals("JackDaniels"))
        {
            String cJackDaniels = String.format (" %.2f",JackDaniels );
            jlblCostOfDrinks.setText(cJackDaniels);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Konyagi"))
        {
            String cKonyagi = String.format (" %.2f",Konyagi );
            jlblCostOfDrinks.setText(cKonyagi);
        }
        
        if (jCmbDrink.getSelectedItem().equals("KenyaCane"))
        {
            String cKenyaCane = String.format (" %.2f",KenyaCane );
            jlblCostOfDrinks.setText(cKenyaCane);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Chrome"))
        {
            String cChrome = String.format (" %.2f",Chrome );
            jlblCostOfDrinks.setText(cChrome);
        }
        
        if (jCmbDrink.getSelectedItem().equals("Heinessy"))
        {
            String cHeinessy = String.format (" %.2f",Heinessy );
            jlblCostOfDrinks.setText(cHeinessy);
        }
    }//GEN-LAST:event_jCmbDrinkActionPerformed

    private void jCDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCDeliveryMouseClicked
        double iDelivery = 100;
        
        if(jCDelivery.isSelected())
        {
            String pDelivery = String.format (" %.2f", iDelivery);
            jlblDeliveryCost.setText (pDelivery);
        }
        else 
        {
            jlblDeliveryCost.setText (null);
        }
    }//GEN-LAST:event_jCDeliveryMouseClicked

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
       System.exit (0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
    /*    jlblDeliveryCost.setText (null);               
        jlblCostOfDrinks.setText(null);
        jlblCostOfMeal.setText(null);
        jlblDeliveryCost.setText(null);
        jtxtTax.setText(null); 
        jtxtSubtotal.setText(null);
        jtxtGrandTotal.setText(null);
    */    
        
        //receipt statements
        double Qty1 = Double.parseDouble(jtxtChicken.getText());
        double Qty2 = Double.parseDouble(jtxtfries.getText());
        double Qty3 = Double.parseDouble(jtxtSausages.getText());
        double Qty4 = Double.parseDouble(jtxtBhajia.getText());
        double price =Double.parseDouble(jtxtGrandTotal.getText());
        jTextArea1.append("\t NICKY'S RESTAURANT SYSTEM: \n\n"  + "Grilled Chicken(400):\t"
                + Qty1 + "\n Fries(100):\t"
                + Qty2 + "\n Sausage(50):\t" 
                + Qty3 + "\n Bhajia(150):\t " 
                +  Qty4 +"\n Total-Price:\t" + price + "\n\n\t THANK YOU FOR VISITING NICKY'S RESTAURANT"+"\n\t WELCOME BACK AGAIN");
        
        
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jChickenGrilledMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickenGrilledMouseClicked
        
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        double cGrilledChicken = Double.parseDouble(jtxtChicken.getText());
        double pGrilledChicken = 600;
         
        
        if ( jChickenGrilled .isSelected() )
        {
             bill = ((cGrilledChicken * pGrilledChicken ) + cMeal);
            String pMeal = String.format (" %.2f", bill);
            jlblCostOfMeal.setText (pMeal);
            
            
        
        }
    }//GEN-LAST:event_jChickenGrilledMouseClicked

    private void jtxtFriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFriesMouseClicked
        
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        double cFries = Double.parseDouble(jtxtfries.getText());
        double pFries = 100;
         
        
        if ( jtxtFries .isSelected() )
        {
             bill =(cFries * pFries ) + cMeal;
             String pMeal = String.format (" %.2f", bill);
            jlblCostOfMeal.setText (pMeal);
            
            
        
        }
    }//GEN-LAST:event_jtxtFriesMouseClicked

    private void jtxtChickenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtChickenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenMouseClicked

    private void jTxtTaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtTaxMouseClicked
                      
            double iTax;
            iTax =bill/100;
            String cTax = String.format(" %.2f",iTax);
            jtxtTax.setText(cTax);
        
    }//GEN-LAST:event_jTxtTaxMouseClicked

    private void jBtnReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnReceiptMouseClicked
        /*jtxtChicken.setText(null);
        jtxtfries.setText(null);
        jtxtSausages.setText(null);
        jtxtBhajia.setText(null);
        jtxtConvert.setText(null);
        jlblConvert.setText("0");
        jlblCostOfMeal.setText("0");
        jlblCostOfDrinks.setText("0");
        jlblDeliveryCost.setText("0");
        jtxtSubtotal.setText("0");
        jtxtTax.setText("0");
        jtxtGrandTotal.setText("0");
        */
        
        double Qty1 = Double.parseDouble(jtxtChicken.getText());
        double Qty2 = Double.parseDouble(jtxtfries.getText());
        double Qty3 = Double.parseDouble(jtxtSausages.getText());
        double Qty4 = Double.parseDouble(jtxtBhajia.getText());
        //double price =Double.parseDouble(jtxtGrandTotal.getText());
        jTextArea1.append("\t NICKY'S RESTAURANT SYSTEM: \n\n"  + "Grilled Chicken(400):\t"
                + Qty1 + "\n Fries(100):\t"
                + Qty2 + "\n Sausage(50): \t" 
                + Qty3 + "\n Bhajia(150): \t " 
                +  Qty4 +"\n\t"+"\n\n\t THANK YOU FOR VISITING NICKY'S RESTAURANT"+"\n\t WELCOME BACK AGAIN");
    }//GEN-LAST:event_jBtnReceiptMouseClicked

    private void jSausageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSausageMouseClicked
        
         
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        double cSausages = Double.parseDouble(jtxtSausages.getText());
        double pSausages = 50;
         
        
        if ( jSausage .isSelected() )
        {
             bill =((cSausages * pSausages ) + cMeal);
            String pMeal = String.format (" %.2f", bill);
            jlblCostOfMeal.setText (pMeal);
            
            
        
        }
                
        
    }//GEN-LAST:event_jSausageMouseClicked

    private void jBhajiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBhajiaMouseClicked
        
         
        double cMeal = Double.parseDouble(jlblCostOfMeal.getText());
        double cBhajia = Double.parseDouble(jtxtBhajia.getText());
        double pBhajia = 150;
         
        
        if ( jBhajia .isSelected() )
        {
             bill =((cBhajia * pBhajia ) + cMeal);
            String pMeal = String.format (" %.2f", bill);
            jlblCostOfMeal.setText (pMeal);
            
            
        
        }
    }//GEN-LAST:event_jBhajiaMouseClicked

    private void jBtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnResetMouseClicked
        
        jtxtChicken.setText(null);
        jtxtfries.setText(null);
        jtxtSausages.setText(null);
        jtxtBhajia.setText(null);
        jtxtConvert.setText(null);
        jlblConvert.setText("0");
        jlblCostOfMeal.setText("0");
        jlblCostOfDrinks.setText("0");
        
        jlblDeliveryCost.setText("0");
        jtxtSubtotal.setText("0");
        jtxtTax.setText("0");
        jtxtGrandTotal.setText("0");
        jCmbDrink.setSelectedIndex(0);
        jcmbCurrency.setSelectedIndex(0);
        jChickenGrilled.setSelected(false);
        jtxtFries.setSelected(false);
        jSausage.setSelected(false);
        jBhajia.setSelected(false);
        jTxtTax.setSelected(false);
        jCDelivery.setSelected(false);


    
    }//GEN-LAST:event_jBtnResetMouseClicked

    private void jCmbDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCmbDrinkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbDrinkMouseClicked

    private void jBtnTotal3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTotal3MouseClicked
        double cTotal1 = Double.parseDouble(jlblCostOfDrinks.getText());
        double cTotal2 = Double.parseDouble(jlblCostOfMeal.getText());
        double cTotal3 = Double.parseDouble(jlblDeliveryCost.getText());
        double cTotal4 = Double.parseDouble(jtxtTax.getText());
        
        //this is a subtotal variable
        double subTotal = (cTotal1+cTotal2+cTotal3);
        //this is a GrandTotal Variable
        double allTotal = (cTotal1+cTotal2+cTotal3+cTotal4);
        
        String SUBTotal = String.format("KSH %.2f", subTotal);
        String ALLTotal = String.format("KSH %.2f", allTotal);

        jtxtGrandTotal.setText(ALLTotal);
        jtxtSubtotal.setText(SUBTotal);
    }//GEN-LAST:event_jBtnTotal3MouseClicked

    private void jtxtChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenActionPerformed

    private void jlblCostOfMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblCostOfMealMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlblCostOfMealMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jBhajia;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnBR;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnCoverter;
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal3;
    private javax.swing.JButton jBtnclear;
    private javax.swing.JButton jBtnequal;
    private javax.swing.JButton jBtnminus;
    private javax.swing.JButton jBtnover;
    private javax.swing.JButton jBtnplus;
    private javax.swing.JButton jBtnpoint;
    private javax.swing.JButton jBtntimes;
    private javax.swing.JCheckBox jCDelivery;
    private javax.swing.JCheckBox jChickenGrilled;
    private javax.swing.JComboBox<String> jCmbDrink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox jSausage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTxtDisplay;
    private javax.swing.JButton jTxtReset;
    private javax.swing.JCheckBox jTxtTax;
    private javax.swing.JComboBox<String> jcmbCurrency;
    private javax.swing.JLabel jlblConvert;
    private javax.swing.JLabel jlblCostOfDrinks;
    private javax.swing.JLabel jlblCostOfMeal;
    private javax.swing.JLabel jlblDeliveryCost;
    private javax.swing.JTextField jtxtBhajia;
    private javax.swing.JTextField jtxtChicken;
    private javax.swing.JTextField jtxtConvert;
    private javax.swing.JCheckBox jtxtFries;
    private javax.swing.JLabel jtxtGrandTotal;
    private javax.swing.JTextField jtxtSausages;
    private javax.swing.JLabel jtxtSubtotal;
    private javax.swing.JLabel jtxtTax;
    private javax.swing.JTextField jtxtfries;
    // End of variables declaration//GEN-END:variables

  
}
